# Generated by Django 4.2 on 2024-05-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(error_messages="Le nom de l'équipe est obligatoire", max_length=64)),
                ('chef', models.CharField(error_messages="Une équipe doit toujours avoir un chef d'équipe", max_length=64)),
            ],
            options={
                'verbose_name': 'Equipes de mission',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages='Email invalide', max_length=255, unique=True)),
                ('nom', models.CharField(error_messages='Le nom est obligatoire', max_length=64)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.CharField(error_messages='Telephone obligatoire', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.team')),
            ],
            options={
                'verbose_name': 'Utilisateurs',
                'ordering': ['-createAt'],
            },
        ),
    ]
