# Generated by Django 4.2 on 2024-05-18 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_superadmin_customuser_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='libelle',
            field=models.CharField(error_messages="Le nom de l'équipe est obligatoire", max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
