# Generated by Django 4.2 on 2024-05-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_team_libelle_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Utilisateurs'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='createAt',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nom',
            field=models.CharField(error_messages='Le nom est obligatoire', max_length=64, verbose_name='full name'),
        ),
    ]
